### PR TITLE
add TouchOSC maps

### PR DESCRIPTION
**Pull request by agraef**
As promised. To keep the main maps directory tidy and clean, these are all in their own subdir, and will also install into their own subdir.

### CODE REVIEW

**Comment by agraef** [comment]
These are all just how to2omm generated them, no manual editing. I did some cursory testing of these to make sure that they all load and work with osc2midi. I also tested the Mix 2 map quite thoroughly, so I'm pretty confident that the maps all work fine. Pd test patches can be found at https://bitbucket.org/agraef/osc2midi-utils.

**Comment by ssj71** [comment]
Beautiful. I think it was very good to make a subdir. And if any of the maps have issues, well, thats why we have a bug tracker. :)

Now I'm the one who needs to get to sleep. I'll see if I can get 0.2 released and announced tomorrow.

Thanks!

**Comment by ssj71** [comment]
Actually, one last thing. Is the touchosc mapping I blindly made before worth keeping? I won't feel bad at all if you think not, considering I've never used the program.

**Comment by agraef** [comment]
> Actually, one last thing. Is the touchosc mapping I blindly made before worth keeping? I won't feel bad at all if you think not, considering I've never used the program.

I'm afraid that It won't fit any of the preinstalled layouts, and none of the others I've seen or made myself either. It might however be useful as a starting point or inspiration for a keyboard-like interface. If you keep it then someone might just come along and create one that fits. :)

**Pull request merged**
