### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by agraef**
Found and fixed two more bugs.

### CODE REVIEW

**Comment by ssj71** [comment]
good catches. Thanks.

**Comment by agraef** [comment]
Thanks! Updated the osc2midi-git/devel packages on the AUR and MacPorts accordingly. (The MacPorts submissions are still pending, but should hopefully be committed soon.)

Maybe it's time for a new release? It's been a while since 0.1.04. :)

**Comment by ssj71** [comment]
I've just been waiting for these to trickle in. If you don't have any more testing planned I'll give it a release. What do you think of calling it 0.2.0?

**Comment by agraef** [comment]
Still running some tests with the rest of the preinstalled TouchOSC layouts, please stay tuned...

**Comment by agraef** [comment]
Looking good. Thumbs up for 0.2.0!

**Comment by agraef** [comment]
Once I get my script to parse all the standard layouts that come with TouchOSC, as a convenience I could just commit the generated omm files, maybe into a subdir like maps/touchosc. Should I?

**Comment by ssj71** [comment]
Absolutely! The more functionality OOTB the better. Please update the readme too so users know they were installed.

**Comment by ssj71** [comment]
what sort of timeline do you expect to have those generated? Would you rather have them be included after 0.2? I'd rather wait I think, but perhaps if it will be some time we shouldn't.

**Comment by agraef** [comment]
Expect them to be ready real soon now. Also, I'm about to submit another pull request since I found some more bugs. So it makes sense to wait a little longer before releasing 0.2.

**Pull request merged**
