### PR TITLE
Latest fixes

### PR DESCRIPTION
**Pull request by agraef**
First commit e5c29ed gets rid of the *.orig files in src, apparently leftovers from running astyle.

### CODE REVIEW

**Comment by agraef** [comment]
Oops, sorry. Apparently I accidentally augmented my existing pull request instead of creating a new one. Anyway, the 2nd and 3rd commit add a README.md which is your README formatted in Markdown. (I also fixed some typos and added a note about to2omm.) Here is how it looks like on Github: https://github.com/agraef/OSC2MIDI. If you like it, we can just remove the old README file.

**Comment by agraef** [comment]
Yeah, I forgot that in order to split pull requests I need to create separate feature branches. Otherwise it just keeps on adding whatever I commit on the master branch. Sorry about that.

Commit cef749a fixes the codes for stop and cont in touchosc.omm which were the wrong way round.

**Comment by ssj71** [comment]
whoops. Thats what I get for using wildcards. 
re: markdown readme I don't really love when a readme isn't readable in the terminal once you download the source, but this one is simple enough that it reads cleanly even as markdown. Thanks.

**Comment by agraef** [comment]
> re: markdown readme I don't really love when a readme isn't readable in the terminal once you download the source, but this one is simple enough that it reads cleanly even as markdown. Thanks.

Yeah, the idea is to keep to the most basic Markdown features so that it looks like you'd write it in plain old ASCII anyway. Ok, if you're fine with it then I'm going to remove the old README file...

**Pull request merged**
