### PR TITLE
fix a small glitch in the DJ mapping

### PR DESCRIPTION
**Pull request by agraef**
I found this while playing around with Control. A test patch for the DJ interface is now available in osc2midi-utils.

### CODE REVIEW

**Comment by ssj71** [comment]
thanks as always!

**Comment by agraef** [comment]
If it works ok for you, can you merge it please? I'm only asking because I'd like to update the Arch and MacPorts packages to the latest revision.

**Comment by ssj71** [comment]
so sorry! I meant to merge it before I left my comment.

**Comment by agraef** [comment]
Thanks!

**Pull request merged**
